filebeat.inputs:
  - type: filestream
    id: chronos-json-logs
    paths:
      - /var/log/chronos/*.log

processors:
  - decode_json_fields:
      fields: ["message"]
      target: ""
      overwrite_keys: true

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  index: "chronos-logs-%{+yyyy.MM.dd}"

setup.kibana:
  host: "http://kibana:5601"
